# ------------------------------
# Base Image
# ------------------------------
    FROM node:20-alpine AS base
    RUN apk add --no-cache libc6-compat
    WORKDIR /app
    
    # ------------------------------
    # Install ALL dependencies
    # (dev + prod) -> needed because of next.config.ts
    # ------------------------------
    FROM base AS deps
    COPY package.json package-lock.json ./
    RUN npm ci   # IMPORTANT: install devDependencies too
    
    # ------------------------------
    # Build Stage
    # ------------------------------
    FROM base AS builder
    WORKDIR /app
    
    # Copy deps
    COPY --from=deps /app/node_modules ./node_modules
    
    # Copy full project
    COPY . .
    
    # Disable telemetry (optional)
    # ENV NEXT_TELEMETRY_DISABLED 1
    
    # Build Next.js app
    RUN npm run build
    
    # ------------------------------
    # Production Runner Image
    # ------------------------------
    FROM node:20-alpine AS runner
    WORKDIR /app
    
    ENV NODE_ENV=production
    ENV PORT=3000
    ENV HOSTNAME=0.0.0.0
    
    # Create user
    RUN addgroup --system --gid 1001 nodejs
    RUN adduser --system --uid 1001 nextjs
    
    # Copy required files from build
    COPY --from=builder /app/public ./public
    COPY --from=builder /app/.next/standalone ./
    COPY --from=builder /app/.next/static ./.next/static
    
    # Permissions
    RUN mkdir -p .next
    RUN chown -R nextjs:nodejs .next
    
    # Expose port
    EXPOSE 3000
    
    # Run as non-root user
    USER nextjs
    
    # Start server generated by Next.js standalone build
    CMD ["node", "server.js"]
    